#!/usr/bin/env bash
# Every fork in the registry has both its issues, on the board, with the body
# the template says — created if missing, corrected if something rewrote them.
#
#   .github/aw/ensure-port-issues.sh
#   ONLY=frogr-rb .github/aw/ensure-port-issues.sh
#   DRY_RUN=1 .github/aw/ensure-port-issues.sh
#
# Bodies are templates, not prose. The `initial-port` agent decides which
# repos are port targets; it does not write these. When it did, all 79 of the
# Gem release issues it created came out at ~860 characters against a 2310
# character template, with the entire release checklist paraphrased away.
set -uo pipefail

ORG=ruby-gtk-project
HUB=$ORG/.github
PROJECT=1
ROOT=$(cd "$(dirname "$0")/../.." && pwd)
TPL=$ROOT/.github/port-issues
REG=$ROOT/port-registry.yml
ONLY=${ONLY:-}
DRY=${DRY_RUN:-}

rc=0
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

say() { printf '%s\n' "$*"; }

python3 - "$REG" > "$work/targets" <<'PY'
import re, sys
text = open(sys.argv[1]).read()
block = text.split('forked:', 1)[1].split('\ncandidates:', 1)[0]
fork = branch = None
for line in block.splitlines():
    m = re.match(r'\s*-\s*fork:\s*(\S+)', line)
    if m:
        fork, branch = m.group(1), 'main'
    m = re.match(r'\s*upstream_branch:\s*(\S+)', line)
    if m and fork:
        print(f'{fork}\t{m.group(1)}')
        fork = None
PY

count=$(wc -l < "$work/targets")
if [ "$count" -eq 0 ]; then
  say "no forks parsed out of the registry — the parse broke, not the registry" >&2
  exit 1
fi
say "$count forks in the registry"

gh project item-list "$PROJECT" --owner "$ORG" --format json --limit 500 \
  --jq '.items[].title' > "$work/board" 2>/dev/null || : > "$work/board"

ensure() { # <repo> <title> <template> <label> <upstream branch>
  local repo=$1 title=$2 tpl=$3 label=$4 upstream=$5 url num have
  sed -e "s/{{REPO}}/$repo/g" -e "s/{{UPSTREAM}}/$upstream/g" "$TPL/$tpl" > "$work/want.md"

  read -r num url < <(gh issue list -R "$HUB" --state all --limit 500 --json title,number,url \
    --jq ".[] | select(.title == \"$title\") | \"\(.number) \(.url)\"" | head -1)

  if [ -z "${num:-}" ]; then
    if [ -n "$DRY" ]; then say "    would create: $title"; return 0; fi
    url=$(gh issue create -R "$HUB" --title "$title" --label "$label" --body-file "$work/want.md") || {
      say "    CREATE FAILED: $title" >&2; rc=1; return 1; }
    say "    created: $title"
  else
    # The footer gh-aw appends is not ours; compare only our part.
    gh issue view "$num" -R "$HUB" --json body -q .body | sed '/^> Generated by /,$d' > "$work/got.md"
    if ! diff -q <(sed -e '$a\' "$work/want.md") <(sed -e '$a\' "$work/got.md") >/dev/null 2>&1; then
      if [ -n "$DRY" ]; then say "    would rewrite body: $title ($(wc -c < "$work/got.md") -> $(wc -c < "$work/want.md") chars)"; return 0; fi
      gh issue edit "$num" -R "$HUB" --body-file "$work/want.md" >/dev/null && say "    body corrected: $title" || {
        say "    EDIT FAILED: $title" >&2; rc=1; }
    fi
  fi

  grep -qxF "$title" "$work/board" && return 0
  [ -n "$DRY" ] && { say "    would add to board: $title"; return 0; }
  gh project item-add "$PROJECT" --owner "$ORG" --url "$url" >/dev/null &&
    say "    on the board: $title"
}

while IFS=$'\t' read -r repo branch; do
  [ -z "$ONLY" ] || [ "$ONLY" = "$repo" ] || continue
  say "=== $repo"
  ensure "$repo" "Initial port: $repo" initial-port.md port "$branch"
  ensure "$repo" "Gem release: $repo" gem-release.md gem-release "$branch"
done < "$work/targets"

say "done (exit $rc)"
exit $rc
